#!/usr/bin/env python3
"""Export AVC fixture JSON dumps into tests/support/AvcDeviceImages.inc.

Matches the style and convention of tests/support/DiceDeviceImages.inc.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


HEADER_TEMPLATE = """// Generated by tools/avc/export_cpp.py from documentation/fixtures/AVC.
// Do not edit by hand: regenerate from the JSON fixtures instead.
#pragma once

#include <cstddef>
#include <cstdint>
#include <span>

namespace ASFW::AVC::Testing {

struct AvcExchangeRecord {
    const char* name;
    std::span<const uint8_t> command;
    std::span<const uint8_t> response;
    uint8_t responseCode;
    uint32_t durationUsec;
    bool ok;
};

struct AvcDeviceImage {
    const char* key;
    const char* modelName;
    const char* vendorName;
    uint64_t guid;
    uint32_t nodeId;
    uint32_t generation;
    const char* driverVersion;
    const char* capturedAt;
    std::span<const AvcExchangeRecord> records;
};

"""

FOOTER_TEMPLATE = """} // namespace ASFW::AVC::Testing
"""


def sanitize_ident(name: str) -> str:
    cleaned = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    if cleaned and cleaned[0].isdigit():
        cleaned = "_" + cleaned
    return cleaned


def to_pascal_case(name: str) -> str:
    words = re.split(r"[-_\s]+", name)
    return "".join(w.capitalize() for w in words if w)


def format_byte_array(var_name: str, bytes_list: list[int]) -> str:
    if not bytes_list:
        return f"inline constexpr uint8_t {var_name}[0] = {{}};\n"
    hex_bytes = ", ".join(f"0x{b:02X}" for b in bytes_list)
    return f"inline constexpr uint8_t {var_name}[] = {{{hex_bytes}}};\n"


def process_device(data: dict) -> str:
    device = data["device"]
    records = data["records"]

    key = device["key"]
    model_name = device["modelName"]
    vendor_name = device["vendorName"]
    guid_str = device["guid"]
    guid_val = int(guid_str, 16) if guid_str.startswith("0x") else int(guid_str)
    node_id = device["nodeId"]
    generation = device["generation"]
    driver_version = device.get("driverVersion", "0.0.0")
    captured_at = device.get("capturedAt", "")

    pascal_name = to_pascal_case(key)
    out = []
    out.append(f"// ---------------------------------------------------------------------------\n")
    out.append(f"// {vendor_name} {model_name} ({key})\n")
    out.append(f"// ---------------------------------------------------------------------------\n\n")

    out.append(f"namespace {pascal_name}Data {{\n\n")

    for i, rec in enumerate(records):
        rec_name = sanitize_ident(rec["name"])
        cmd_bytes = rec["command"]
        resp_bytes = rec.get("response") or []

        out.append(format_byte_array(f"kCmd_{i}_{rec_name}", cmd_bytes))
        if resp_bytes:
            out.append(format_byte_array(f"kResp_{i}_{rec_name}", resp_bytes))
        out.append("\n")

    out.append(f"inline constexpr AvcExchangeRecord kRecords[] = {{\n")
    for i, rec in enumerate(records):
        rec_name = sanitize_ident(rec["name"])
        resp_bytes = rec.get("response") or []
        resp_code = rec.get("responseCode") or (resp_bytes[0] if resp_bytes else 0)
        dur = rec.get("durationUsec") or 0
        ok_str = "true" if rec.get("ok", False) else "false"

        cmd_span = f"kCmd_{i}_{rec_name}"
        resp_span = f"kResp_{i}_{rec_name}" if resp_bytes else "std::span<const uint8_t>{}"

        out.append(f"    {{\"{rec['name']}\", {cmd_span}, {resp_span}, 0x{resp_code:02X}, {dur}U, {ok_str}}},\n")

    out.append("};\n\n")
    out.append(f"}} // namespace {pascal_name}Data\n\n")

    const_name = f"k{pascal_name}"
    out.append(f"inline constexpr AvcDeviceImage {const_name}{{\n")
    out.append(f"    .key = \"{key}\",\n")
    out.append(f"    .modelName = \"{model_name}\",\n")
    out.append(f"    .vendorName = \"{vendor_name}\",\n")
    out.append(f"    .guid = 0x{guid_val:016X}ULL,\n")
    out.append(f"    .nodeId = {node_id}U,\n")
    out.append(f"    .generation = {generation}U,\n")
    out.append(f"    .driverVersion = \"{driver_version}\",\n")
    out.append(f"    .capturedAt = \"{captured_at}\",\n")
    out.append(f"    .records = {pascal_name}Data::kRecords,\n")
    out.append("};\n\n")

    return "".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fixtures-dir", default="documentation/fixtures/AVC", help="Directory containing JSON fixtures")
    parser.add_argument("--output", default="tests/support/AvcDeviceImages.inc", help="Target C++ include file")
    args = parser.parse_args()

    fixtures_path = Path(args.fixtures_dir)
    if not fixtures_path.exists():
        print(f"Error: Fixtures dir {fixtures_path} does not exist.", file=sys.stderr)
        return 1

    json_files = sorted(fixtures_path.glob("*.json"))
    if not json_files:
        print(f"Warning: No JSON fixture files found in {fixtures_path}.", file=sys.stderr)

    out_content = [HEADER_TEMPLATE]
    for jf in json_files:
        print(f"Processing {jf}...")
        with open(jf, "r", encoding="utf-8") as f:
            data = json.load(f)
        out_content.append(process_device(data))

    out_content.append(FOOTER_TEMPLATE)

    out_path = Path(args.output)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("".join(out_content))

    print(f"Exported {len(json_files)} device image(s) to {out_path}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
