"""Export a filtered phase-0 reference capture as a C++ fixture include."""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import struct

from .log_parser import LogEvent, parse_log
from .parity_phase0 import collect_phase0_events, region_from_event
from .semantic_analysis import SessionAnalysis, analyze_session


STAGE_PREPARE = "prepare"
STAGE_IRM_PLAYBACK = "irm_playback"
STAGE_PROGRAM_RX = "program_rx"
STAGE_IRM_CAPTURE = "irm_capture"
STAGE_PROGRAM_TX_ENABLE = "program_tx_enable"
STAGE_ORDER = (
    STAGE_PREPARE,
    STAGE_IRM_PLAYBACK,
    STAGE_PROGRAM_RX,
    STAGE_IRM_CAPTURE,
    STAGE_PROGRAM_TX_ENABLE,
)
STAGE_CONST = {
    STAGE_PREPARE: "Prepare",
    STAGE_IRM_PLAYBACK: "IrmPlayback",
    STAGE_PROGRAM_RX: "ProgramRx",
    STAGE_IRM_CAPTURE: "IrmCapture",
    STAGE_PROGRAM_TX_ENABLE: "ProgramTxEnable",
}
REQUEST_KIND = {
    "Qread": "Read",
    "Bread": "Read",
    "Qwrite": "Write",
    "LockRq": "Lock",
}
RESPONSE_KIND = {
    "QRresp": "Read",
    "BRresp": "Read",
    "LockResp": "Lock",
}
SUCCESS_STATUS = "AsyncStatus::kSuccess"


@dataclass(frozen=True)
class FixtureRequest:
    stage: str
    kind: str
    address_hi: int
    address_lo: int
    length: int
    speed: str
    response_length: int
    payload: bytes


@dataclass(frozen=True)
class FixtureResponse:
    stage: str
    kind: str
    address_hi: int
    address_lo: int
    request_length: int
    response_length: int
    speed: str
    status: str
    payload: bytes


@dataclass(frozen=True)
class FixtureData:
    source_label: str
    ignore_config_rom: bool
    requests: list[FixtureRequest]
    responses: list[FixtureResponse]


def load_and_export_parity_cpp_fixture(
    log_path: str | Path,
    out_path: str | Path,
    *,
    ignore_config_rom: bool = False,
) -> Path:
    session = load_and_analyze_session(log_path)
    return export_parity_cpp_fixture(
        session,
        log_path,
        out_path,
        ignore_config_rom=ignore_config_rom,
    )


def load_and_analyze_session(log_path: str | Path) -> SessionAnalysis:
    text = Path(log_path).read_text(encoding="utf-8", errors="replace")
    return analyze_session(parse_log(text), Path(log_path).name)


def export_parity_cpp_fixture(
    session: SessionAnalysis,
    source_path: str | Path,
    out_path: str | Path,
    *,
    ignore_config_rom: bool = False,
) -> Path:
    rendered = render_parity_cpp_fixture(
        session,
        source_label=Path(source_path).name,
        ignore_config_rom=ignore_config_rom,
    )
    target = Path(out_path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(rendered, encoding="utf-8")
    return target


def render_parity_cpp_fixture(
    session: SessionAnalysis,
    *,
    source_label: str,
    ignore_config_rom: bool = False,
) -> str:
    fixture = _build_fixture_data(
        session,
        source_label=source_label,
        ignore_config_rom=ignore_config_rom,
    )

    byte_arrays: list[tuple[str, bytes]] = []
    request_payload_exprs: list[str] = []
    for index, request in enumerate(fixture.requests):
        request_payload_exprs.append(
            _register_payload(byte_arrays, f"RequestPayload{index:03d}", request.payload)
        )

    response_payload_exprs: list[str] = []
    for index, response in enumerate(fixture.responses):
        response_payload_exprs.append(
            _register_payload(byte_arrays, f"ResponsePayload{index:03d}", response.payload)
        )

    lines = [
        "// Generated by `pydice export-parity-cpp` from the FireBug reference trace.",
        "// This file is intentionally checked in: it is the executable phase-0 oracle.",
        "",
        "namespace ReferencePhase0ParityFixture {",
        "",
        f'inline constexpr char kSourceLog[] = "{fixture.source_label}";',
        f"inline constexpr bool kIgnoreConfigRom = {'true' if fixture.ignore_config_rom else 'false'};",
        "inline constexpr bool kSkipInitialIRMCompareVerify = true;",
        "inline constexpr bool kExcludeIncomingRemoteWrites = true;",
        "",
    ]

    for name, payload in byte_arrays:
        if not payload:
            continue
        lines.extend(_render_byte_array(name, payload))
        lines.append("")

    lines.extend(
        _render_request_array("kFullExpectedRequests", fixture.requests, request_payload_exprs)
    )
    lines.append("")
    lines.extend(
        _render_response_array("kFullResponseSteps", fixture.responses, response_payload_exprs)
    )
    lines.append("")

    for stage in STAGE_ORDER:
        stage_requests = [req for req in fixture.requests if req.stage == stage]
        stage_responses = [resp for resp in fixture.responses if resp.stage == stage]
        request_exprs = [
            request_payload_exprs[index]
            for index, req in enumerate(fixture.requests)
            if req.stage == stage
        ]
        response_exprs = [
            response_payload_exprs[index]
            for index, resp in enumerate(fixture.responses)
            if resp.stage == stage
        ]
        lines.extend(
            _render_request_array(
                f"k{STAGE_CONST[stage]}ExpectedRequests",
                stage_requests,
                request_exprs,
            )
        )
        lines.append("")
        lines.extend(
            _render_response_array(
                f"k{STAGE_CONST[stage]}ResponseSteps",
                stage_responses,
                response_exprs,
            )
        )
        lines.append("")

    lines.append("} // namespace ReferencePhase0ParityFixture")
    return "\n".join(lines).rstrip() + "\n"


def _build_fixture_data(
    session: SessionAnalysis,
    *,
    source_label: str,
    ignore_config_rom: bool,
) -> FixtureData:
    phase0_events = collect_phase0_events(session, ignore_config_rom=ignore_config_rom)
    requests: list[FixtureRequest] = []
    responses: list[FixtureResponse] = []

    stage = STAGE_PREPARE
    for item in phase0_events:
        event = item.event
        if event.kind == "BusReset":
            continue

        region = region_from_event(event)
        if region is None:
            continue

        if stage == STAGE_PREPARE and region.startswith("ffff.f000.022"):
            stage = STAGE_IRM_PLAYBACK
        elif stage == STAGE_PROGRAM_RX and region.startswith("ffff.f000.022"):
            stage = STAGE_IRM_CAPTURE

        if event.kind in REQUEST_KIND and _is_driver_outbound_request(event):
            address_hi, address_lo = _parse_address(region)
            payload = _request_payload(event)
            requests.append(
                FixtureRequest(
                    stage=stage,
                    kind=REQUEST_KIND[event.kind],
                    address_hi=address_hi,
                    address_lo=address_lo,
                    length=_request_length(event),
                    speed=event.speed or "s100",
                    response_length=_response_length_for_request(phase0_events, item.event_index, event),
                    payload=payload,
                )
            )
        elif event.kind in RESPONSE_KIND:
            address_hi, address_lo = _parse_address(region)
            responses.append(
                FixtureResponse(
                    stage=stage,
                    kind=RESPONSE_KIND[event.kind],
                    address_hi=address_hi,
                    address_lo=address_lo,
                    request_length=_request_length_for_response(phase0_events, item.event_index, event),
                    response_length=_response_length(event),
                    speed=event.speed or "s100",
                    status=SUCCESS_STATUS,
                    payload=_response_payload(event),
                )
            )

        if stage == STAGE_IRM_PLAYBACK and event.kind == "LockResp" and region == "ffff.f000.0224":
            stage = STAGE_PROGRAM_RX
        elif stage == STAGE_IRM_CAPTURE and event.kind == "LockResp" and region == "ffff.f000.0224":
            stage = STAGE_PROGRAM_TX_ENABLE

    return FixtureData(
        source_label=source_label,
        ignore_config_rom=ignore_config_rom,
        requests=requests,
        responses=responses,
    )


def _is_driver_outbound_request(event: LogEvent) -> bool:
    if event.kind == "Qwrite":
        return event.src.lower() == "ffc0"
    return event.kind in REQUEST_KIND


def _parse_address(region: str) -> tuple[int, int]:
    high, mid, low = region.split(".")
    return int(high, 16), (int(mid, 16) << 16) | int(low, 16)


def _request_length(event: LogEvent) -> int:
    if event.kind in {"Qread", "Qwrite"}:
        return 4
    return event.size or 0


def _response_length(event: LogEvent) -> int:
    if event.kind == "QRresp":
        return 4
    return event.size or 0


def _request_payload(event: LogEvent) -> bytes:
    if event.kind == "Qwrite":
        return struct.pack(">I", event.value or 0)
    return event.payload or b""


def _response_payload(event: LogEvent) -> bytes:
    if event.kind == "QRresp":
        return struct.pack(">I", event.value or 0)
    return event.payload or b""


def _response_length_for_request(
    phase0_events: list,
    event_index: int,
    event: LogEvent,
) -> int:
    if event.kind != "LockRq":
        return 0
    for item in phase0_events:
        later = item.event
        if item.event_index <= event_index:
            continue
        if later.kind != "LockResp":
            continue
        if later.tLabel == event.tLabel and later.address == event.address:
            return later.size or 0
    return 0


def _request_length_for_response(
    phase0_events: list,
    event_index: int,
    event: LogEvent,
) -> int:
    for item in reversed(phase0_events):
        earlier = item.event
        if item.event_index >= event_index:
            continue
        if event.kind == "QRresp" and earlier.kind != "Qread":
            continue
        if event.kind == "BRresp" and earlier.kind != "Bread":
            continue
        if event.kind == "LockResp" and earlier.kind != "LockRq":
            continue
        if earlier.tLabel == event.tLabel and earlier.address == event.address:
            return _request_length(earlier)
    return 0


def _register_payload(
    byte_arrays: list[tuple[str, bytes]],
    name: str,
    payload: bytes,
) -> str:
    if not payload:
        return "ByteView{nullptr, 0}"
    array_name = f"k{name}"
    byte_arrays.append((array_name, payload))
    return f"ByteView{{{array_name}.data(), {array_name}.size()}}"


def _render_byte_array(name: str, payload: bytes) -> list[str]:
    lines = [f"inline constexpr std::array<uint8_t, {len(payload)}> {name}{{{{"]
    for offset in range(0, len(payload), 12):
        chunk = payload[offset : offset + 12]
        body = ", ".join(f"0x{byte:02X}" for byte in chunk)
        lines.append(f"    {body},")
    lines.append("}};")
    return lines


def _render_request_array(
    name: str,
    requests: list[FixtureRequest],
    payload_exprs: list[str],
) -> list[str]:
    lines = [f"inline constexpr std::array<ExpectedRequest, {len(requests)}> {name}{{{{"]
    for request, payload_expr in zip(requests, payload_exprs):
        lines.append(
            "    ExpectedRequest{"
            f"OpKind::{request.kind}, "
            f"0x{request.address_hi:04X}U, "
            f"0x{request.address_lo:08X}U, "
            f"{request.length}U, "
            f"{_speed_literal(request.speed)}, "
            f"{request.response_length}U, "
            f"{payload_expr}"
            "},"
        )
    lines.append("}};")
    return lines


def _render_response_array(
    name: str,
    responses: list[FixtureResponse],
    payload_exprs: list[str],
) -> list[str]:
    lines = [f"inline constexpr std::array<ResponseStep, {len(responses)}> {name}{{{{"]
    for response, payload_expr in zip(responses, payload_exprs):
        lines.append(
            "    ResponseStep{"
            f"OpKind::{response.kind}, "
            f"0x{response.address_hi:04X}U, "
            f"0x{response.address_lo:08X}U, "
            f"{response.request_length}U, "
            f"{response.response_length}U, "
            f"{_speed_literal(response.speed)}, "
            f"{response.status}, "
            f"{payload_expr}"
            "},"
        )
    lines.append("}};")
    return lines


def _speed_literal(speed: str) -> str:
    mapping = {
        "s100": "FwSpeed::S100",
        "s200": "FwSpeed::S200",
        "s400": "FwSpeed::S400",
        "s800": "FwSpeed::S800",
        "s1600": "FwSpeed::S1600",
        "s3200": "FwSpeed::S3200",
    }
    return mapping[speed.lower()]
